name: mi_card
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - images/
  fonts:
    - family: Merriweather
      fonts:
        - asset: fonts/Merriweather/Merriweather-Regular.ttf

    - family: Source Sans Pro
      fonts:
        - asset: fonts/Source_Sans_3/static/SourceSans3-Regular.ttf

    - family: Ubuntu
      fonts:
        - asset: fonts/Ubuntu/Ubuntu-Regular.ttf
